### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by nthanfp** [kamronbek29/tiktok_views#2]
Hello, I'm just try your script, its working but my views not increase. why?
Paste video url here: https://www.tiktok.com/@nthanfp/video/6881551033714216194
Made 10 successful shares
Made 20 successful shares
Made 30 successful shares
Made 40 successful shares
Made 50 successful shares
Made 60 successful shares
Made 70 successful shares
Made 80 successful shares
Made 90 successful shares
Made 100 successful shares
Made 110 successful shares
Made 120 successful shares

**Comment by kamronbek29** [comment]
Hi, i just now updated a script, try it. For me it worked
